[pytest]
# --headless: 开启无头模式（不弹浏览器界面，速度更快，CI服务器必备）
# --video=retain-on-failure: 只有在用例失败时，才保存录屏！
# --screenshot=only-on-failure: 只有在用例失败时，才保存网页截图！
# --html=report.html: 跑完后自动生成一份网页版的测试报告
addopts = --browser chromium --video=retain-on-failure --screenshot=only-on-failure --html=report.html